@baseURL = http://localhost:8080/api/v1

GET {{baseURL}}/opening

###
POST {{baseURL}}/opening
Content-Type: application/json

{
    "role":"Senior da vida com Go",
    "company":"Ultrasoft",
    "location":"new york",
    "remote":true,
    "link":"vaga.com",
    "salary":522000
}

###
DELETE {{baseURL}}/opening

###
PUT {{baseURL}}/opening

###
GET {{baseURL}}/openings