@baseURL = http://localhost:8080/api/v1

GET {{baseURL}}/opening?id=3

###
POST {{baseURL}}/opening
Content-Type: application/json

{
    "role":"{text}",
    "company":"{text}",
    "location":"{text}",
    "remote":true,
    "link":"{text}",
    "salary":5000
}

###
DELETE {{baseURL}}/opening?id={id}

###
PUT {{baseURL}}/opening?id={id}
Content-Type: application/json

{
    "role":"{text}",
    "company":"{text}"
}

###
GET {{baseURL}}/openings